version: '3.8'

services:
  # Serviço da API FastAPI
  api:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: central_atendimento_api
    command: gunicorn -w 4 -k uvicorn.workers.UvicornWorker src.main:app --bind 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - ./backend/src:/app/src # Monta o código-fonte para live-reloading (opcional, bom para dev)
    env_file:
      - ./backend/.env # Carrega as variáveis de ambiente do arquivo .env
    depends_on:
      db:
        condition: service_healthy # Espera o banco de dados estar saudável antes de iniciar a API
    restart: on-failure

  # Serviço do Banco de Dados PostgreSQL
  db:
    image: postgres:14-alpine
    container_name: central_atendimento_db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432" # Expõe a porta do banco para o host (opcional, bom para debug)
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always

volumes:
  postgres_data:
    driver: local
